### ISSUE TITLE
Missing App icon with Android 7.0

### ISSUE THREAD

**Issue by Sami32** [myBraavos/starknet-meta#76]
Hello there!

Since this issue is still here after months and that your Play Store contact seem to be a dead end, here i'm posting the issue that you'll make reach your Android developper.

![IMG_20240125_153316](https://github.com/myBraavos/starknet-meta/assets/18471069/74e52dcc-d515-4b92-be12-5126f3034fec)

As showed above, your App use the default Android icon with Android 7.0 (Xiaomi)

Regards,

**Comment by avimak** [comment]
Thanks for letting us know, we will handle it ASAP 🙏
